config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, as: :admin_users, path: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  get 'send_product_mail/:id', to: 'products#send_product_mail', as: 'send_product_mail'

  get 'products/index'
  resources :products
  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :attachement, AttachementUploader

  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    # to user devise to filter products:
    # @product = current_user.products.new
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create

    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_product_mail
    @product = Product.find(params[:id])
    @user = current_user
    UserMailer.with(product: @product, user: @user).product_email.deliver
    # UserMailer.product_email(product: @product, user: @user).deliver
    flash[:notice] = "An email with further information has been sent."
    redirect_to products_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :attachement, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :attachement, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :attachement, :class => 'form-control' %>
    </div>
    <%=f.error_span(:attachement) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:attachement) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <% if product.attachement.url %>
        <td><%= image_tag (product.attachement.url), class: 'product-image' %></td>
        <% else %>
        <td></td>
        <% end %>
        <td>
          <% if can? :read, product %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'More Info', 
                      send_product_mail_path(product), 
                      class: "btn btn-default btn-xs" %>
          <% end %>
          <% if can? :update, product %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, product %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        product_path(product),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="col-lg-3">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_product_path,
              :class => 'btn btn-lg btn-primary' %>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @product.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachement) %>:</strong></dt>
  <% if @product.attachement.url %>
  <dd><%= image_tag(@product.attachement.url) %></dd>
  <% else %>
  <dd></dd>
  <% end %>
</dl>

<% if can? :read, @product %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
  products_path, :class => 'btn btn-default'  %>
<% end %>
<% if can? :update, @product %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_product_path(@product), :class => 'btn btn-default' %>
<% end %>
<% if can? :destroy, @product %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                product_path(@product),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>