config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, as: :admin_users, path: 'users'
  post 'create_user', to: 'users#create', as: 'create_user'
  get 'send_product_mail/:id', to: 'products#send_product_mail', as: 'send_product_mail'

  get 'products/index'
  resources :products
  root 'products#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBoilerplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= nav_bar :static => :top, :brand => "CutiePies" do %>
      <% menu_group :pull => :right do %>
        <% if current_user %>
          <%= menu_item "Home", products_index_path %>
          <%= menu_item "Edit Profile", edit_user_registration_path %>
          <% if current_user.admin? %>
            <%= menu_item "Register users", new_admin_user_path %>
            <%= menu_item "Overview users", admin_users_path %>
          <% end %>
          <%= menu_item "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= menu_item "Login",new_user_session_path %>  
        <% end %>
      <% end %>
    <% end %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>